# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSet', models.FileField(upload_to='getUploadedFileName')),
            ],
        ),
    ]
