# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='dataSet',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
