# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160210_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 15, 51, 19, 819820, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='getUploadedFileName'),
        ),
    ]
