# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 16:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20160210_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 10, 16, 37, 11, 365240, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='text',
            field=models.TextField(default=datetime.datetime(2016, 2, 10, 16, 37, 35, 583406, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
