# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160210_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='author',
        ),
    ]
