# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_uploadfile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='text',
        ),
    ]
